name: StaffChatPE
main: StaffChatPE\Main
version: "2.0.1"
api: [3.0.0]
load: STARTUP
author: VMPE Development Team
description: StaffChat plugin.
website: Not showing.

commands:
 staffchat:
   aliases: [sc]
   description: StaffChatPE commands.
permissions:
 staffchat.*:
  default: false
  description: StaffChatPE permissions.
  children:
   staffchat.channels:
    default: false
    description: StaffChatPE channels permissions.
   staffchat.commands:
    default: false
    description: StaffChatPE commands permissions.
    children:
      staffchat.help:
       default: false
       description: StaffChatPE command Help permission.
      staffchat.list:
      default: false
      description: StaffChatPE command list permission.
      staffchat.chat:
      default: false
      description: Allows you to chat / see chat.
      staffchat.info:
       default: false
       description: StaffChatPE command Info permission.
      staffchat.reload:
       default: false
       description: StaffChatPE command Reload permission.
      staffchat.list:
       default: false
       description: StaffChatPE command List permission.
      staffchat.join:
       default: false
       description: StaffChatPE command Join permission.
      staffchat.leave:
       default: false
       description: StaffChatPE command Leave permission.
      staffchat.new:
       default: false
       description: StaffChatPE command New permission.
